xrOxygen/xray-oxygen

- code/engine.vc2008/xrGame/console_commands.cpp
Spawn items, as in the old builds.
> ADD: command "g_spawn" from LA.

- code/engine.vc2008/xrEngine/Device_wndproc.cpp
Thanks to @nitrocaster
From:
https://github.com/OpenXRay/xray-16/commit/169b901e493a2c1af4c80a5de8ef3cf7cd7ad66a
> Prevent 'ding' sounds caused by Alt+key combinations.

- game/gamedata/configs/ui/ui_keybinding.xml
- game/gamedata/configs/ui/ui_mm_opt.xml
- game/gamedata/configs/ui/ui_mm_opt_16.xml
- game/gamedata/scripts/ui_mm_opt_gameplay.script
Удалил неиспользуемые кнопки в настройках.
> * DEL: Removes unused buttons.

- code/engine.vc2008/xrRender/xrRender/Blender_BmmD.cpp
- code/engine.vc2008/xrRender/xrRender/SH_Texture.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2.cpp
> * ADD: Added key "-render_for_weak_systems" simplify R2 (r2a)

- code/engine.vc2008/xrRender/xrRenderPC_R2/r2.cpp
> * FIX: Fixed broken -noshadows key

- code/engine.vc2008/xrGame/game_graph_inline.h
> * FIX: Workaround with valid game vertex.

- code/utils/xrAI/game_graph_builder.cpp
> * EDIT: Some ai-node is not connected to AI-map.

- code/utils/xrAI/xrAI.cpp
> Silent Key xrAI

- code/engine.vc2008/xrRender/xrRender/SkeletonX.cpp
- game/gamedata/shaders/r2/skin.h
Из OGSR.
На r2 должно заработать, а на более старшие рендеры надо писать полностью новый шейдер, судя по всему. Т.к. код шейдера сильно отличается.
Не забывайте очищать шейдерный кэш, при экспериментах со скиннингом.
> Переделал скиннинг на кватернионы

- code/engine.vc2008/xrGame/alife_object.cpp
- code/engine.vc2008/xrServerEntities/xrServer_Objects_ALife_Items.cpp
- code/engine.vc2008/xrServerEntities/xrServer_Objects_ALife_Items.h
> * FIX: Broken alt scopes system.

- code/engine.vc2008/xrCore/DebugCore/dxerr.cpp
- code/engine.vc2008/xrEngine/ClS/NET_Client.cpp
- code/engine.vc2008/xrEngine/ClS/NET_Client.h
- code/engine.vc2008/xrEngine/ClS/NET_Common.cpp
- code/engine.vc2008/xrEngine/ClS/NET_Common.h
- code/engine.vc2008/xrEngine/ClS/NET_Server.cpp
- code/engine.vc2008/xrEngine/ClS/NET_Server.h
- code/engine.vc2008/xrEngine/IGame_Level.h
- code/engine.vc2008/xrEngine/Text_Console.cpp
- code/engine.vc2008/xrGame/Actor.cpp
- code/engine.vc2008/xrGame/Level.cpp
- code/engine.vc2008/xrGame/Level.h
- code/engine.vc2008/xrGame/Level_network_Demo.cpp
- code/engine.vc2008/xrGame/Level_network_messages.cpp
- code/engine.vc2008/xrGame/Message_Filter.cpp
- code/engine.vc2008/xrGame/NET_Queue.h
- code/engine.vc2008/xrGame/console_commands.cpp
- code/engine.vc2008/xrGame/game_cl_base.h
- code/engine.vc2008/xrGame/game_sv_base.cpp
- code/engine.vc2008/xrGame/game_sv_base.h
- code/engine.vc2008/xrGame/xrServer.cpp
- code/engine.vc2008/xrGame/xrServer.h
- code/engine.vc2008/xrGame/xrServer_process_event_destroy.cpp
- code/engine.vc2008/xrServerEntities/xrMessages.h
> Minor xrServer cleanup (#103)

- game/gamedata/scripts/xr_hear.script
> убраны лишние пробелы

- game/gamedata/configs/system.ltx
> Translation of comments with a bad coding system.ltx

- code/engine.vc2008/xrEngine/Rain.cpp
- code/engine.vc2008/xrEngine/Rain.h
- code/engine.vc2008/xrRender/xrRender/Blender_Recorder_StandartBinding.cpp
- code/engine.vc2008/xrRender/xrRender/dxRainRender.cpp
- game/gamedata/shaders/r2/ps_water.hlsl
- game/gamedata/shaders/r2/vs_water.hlsl
> * FIX: Corrected not puddling puddles.

- code/engine.vc2008/xrGame/console_commands.cpp
- code/engine.vc2008/xrGame/ui/UIMMShniaga.cpp
> Crashes fixed

- code/engine.vc2008/xrRender/xrRender/LightTrack.cpp
- code/engine.vc2008/xrRender/xrRender/Light_DB.cpp
- code/engine.vc2008/xrRender/xrRender/Light_DB.h
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2.h
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2_R_render.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2_R_sun.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2_rendertarget_accum_direct.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R2/r2_rendertarget_phase_combine.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R3/r2_R_sun.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R3/r3.h
- code/engine.vc2008/xrRender/xrRenderPC_R3/r3_R_render.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R3/r3_rendertarget_accum_direct.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R3/r3_rendertarget_phase_combine.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R4/r2_R_sun.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R4/r4.h
- code/engine.vc2008/xrRender/xrRenderPC_R4/r4_R_render.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R4/r4_rendertarget_accum_direct.cpp
- code/engine.vc2008/xrRender/xrRenderPC_R4/r4_rendertarget_phase_combine.cpp
> * EDIT: Correct sunlight orientation

- code/engine.vc2008/xrGame/IKLimb.cpp
> * FIX: Fixed crash in bones callbacks.

- game/gamedata/shaders/r2/common.h
> * ADD: Shadows from clouds on R2.

- code/engine.vc2008/xrEngine/CameraBase.cpp
- code/engine.vc2008/xrEngine/CameraBase.h
- code/engine.vc2008/xrEngine/CameraDefs.h
- code/engine.vc2008/xrEngine/CameraManager.cpp
- code/engine.vc2008/xrEngine/CameraManager.h
- code/engine.vc2008/xrEngine/xr_efflensflare.cpp
> CCameraManager extension, fixed sun flare flickering in 1st person view. 

- code/engine.vc2008/xrGame/Level_network.cpp
- code/engine.vc2008/xrGame/Level_network_messages.cpp
- code/engine.vc2008/xrGame/alife_storage_manager.cpp
- code/engine.vc2008/xrGame/alife_storage_manager.h
- code/engine.vc2008/xrGame/alife_storage_manager_inline.h
- code/engine.vc2008/xrGame/alife_update_manager.cpp
- code/engine.vc2008/xrGame/console_commands.cpp
- code/engine.vc2008/xrGame/game_sv_base.cpp
- code/engine.vc2008/xrGame/game_sv_base.h
- code/engine.vc2008/xrGame/xrGame.vcxproj
- code/engine.vc2008/xrGame/xrGame.vcxproj.filters
- code/engine.vc2008/xrGame/xrServer.cpp
- code/engine.vc2008/xrGame/xrServer_process_event_destroy.cpp
- code/engine.vc2008/xrGame/xrServer_process_event_ownership.cpp
- code/engine.vc2008/xrGame/xrServer_process_event_reject.cpp
- code/engine.vc2008/xrServerEntities/xrMessages.h
This reverts commit 7ecd0573d3cbf1e3b1648d28bb75151282fd497f.
> Revert "* DEL: Cleanup xrServer and xrMessages." (problems with saves)

- code/engine.vc2008/xrCore/_vector2.h
- code/engine.vc2008/xrCore/_vector3d.h
- code/engine.vc2008/xrCore/_vector4.h
- code/engine.vc2008/xrScripts/export/script_fvector_script.cpp
- game/gamedata/shaders/r3/ps_rain_apply_gloss.hlsl
- game/gamedata/shaders/r3/ps_rain_patch_normal.hlsl
> Ox-dev Update

- game/gamedata/configs/zones/zone_campfire.ltx
>  *ADD: enabling_sound for a campfire in the config

- code/engine.vc2008/xrGame/Grenade.cpp
- code/engine.vc2008/xrGame/ui/UIDragDropListEx.cpp
> * FIX: grenade's condtion

- code/engine.vc2008/xrGame/Grenade.cpp
- code/engine.vc2008/xrGame/Grenade.h
- code/engine.vc2008/xrGame/inventory_item.h
> * FIX: grenade's condtion (#2)

- game/gamedata/configs/system.ltx
Удалена никогда не используемая мультиплеерная секция
> Удалена никогда не используемая секция

- game/gamedata/configs/ui/ui_mm_main.xml
> Удалена часть относящаяся к мультиплееру

- game/gamedata/configs/ui/ui_HUD_16.xml
Поправлено положение миникарты и некоторые малозаметные правки
> Поправлено положение миникарты

- game/gamedata/configs/ui/ui_mm_opt_16.xml
Исправлено растяжение чекера "статические glows", расширен список строк для выбора сглаживания, удалены сегменты отвечающие за полосу загрузки мультиплеерной карты или патча (эта функция я так понял убрана)
> Исправлено растяжение чекера "статические glows"

- code/engine.vc2008/xrGame/Actor.cpp
- code/engine.vc2008/xrGame/console_commands.cpp
> Feature: third person camera switching using console command

- game/gamedata/configs/text/eng/st_items_equipment.xml
- game/gamedata/configs/text/eng/ui_st_cheat.xml
- game/gamedata/configs/text/eng/ui_st_debug_options.xml
- game/gamedata/configs/text/eng/ui_st_inventory.xml
- game/gamedata/configs/text/eng/ui_st_keybinding.xml
- game/gamedata/configs/text/eng/ui_st_loadscreen.xml
- game/gamedata/configs/text/eng/ui_st_mm.xml
- game/gamedata/configs/text/eng/ui_st_pda.xml
- game/gamedata/configs/text/eng/ui_st_screen.xml
--note--
most of the strings that were only in the russian locale were translated using google translate,
however i did try to make sure that the text that was translated was relevant to the unlocalized name from the files, but given that i don't speak russian, i can't guarantee 100% accuracy of the translation.
the rest of the text was merged from the actual english translation shipped with the game using win-merge.
i also tried to bring the english localized strings present in the xml's in line with the ones from the russian files
> Attempt at enhancing the localization for english.

- code/engine.vc2008/xrCDB/ISpatial_q_box.cpp
- code/engine.vc2008/xrCDB/ISpatial_q_frustum.cpp
- code/engine.vc2008/xrCDB/ISpatial_q_ray.cpp
- code/engine.vc2008/xrCDB/xrCDB.h
- code/engine.vc2008/xrCDB/xrCDB_Collector.cpp
- code/engine.vc2008/xrCore/Envelope.cpp
> Some small changes

- code/engine.vc2008/xrEngine/FDemoRecord.cpp
- code/engine.vc2008/xrGame/HUDCrosshair.cpp
- code/engine.vc2008/xrGame/ai/monsters/basemonster/base_monster_debug.cpp
- code/engine.vc2008/xrGame/ai/stalker/ai_stalker_debug.cpp
- code/engine.vc2008/xrGame/level_debug.cpp
- code/engine.vc2008/xrGame/level_graph_debug.cpp
- code/engine.vc2008/xrGame/level_graph_debug2.cpp
- code/engine.vc2008/xrGame/space_restrictor.cpp
- code/engine.vc2008/xrRender/xrRender/occRasterizer.cpp
> Fixed mixed and debug build

- code/engine.vc2008/xrPlay/entry_point.cpp
> Command-line param that clears shader cache every time game launches

- code/SDK/include/AnselSDK/ansel/Configuration.h
> * MRG: Vertver2ForserX
